spring.application.name=backend

# Server Port Configuration
server.port=8080

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/student_tracker
spring.datasource.username=student_user
spring.datasource.password=userpassword22

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable OSIV warning
spring.jpa.open-in-view=false